export interface LeaderboardEntry {
  id: number;
  username: string;
  score: number;
  gold: number;
  elo: number;
  wins: number;
  losses: number;
}

export const dummyData: LeaderboardEntry[] = [
  {
    id: 1,
    username: 'Player 1',
    score: 1500,
    gold: 1200,
    elo: getRandomElo(),
    wins: 75,
    losses: 25,
  },
  {
    id: 2,
    username: 'Player 2',
    score: 1400,
    gold: 1100,
    elo: getRandomElo(),
    wins: 68,
    losses: 32,
  },
  {
    id: 3,
    username: 'Player 3',
    score: 1300,
    gold: 900,
    elo: getRandomElo(),
    wins: 60,
    losses: 40,
  },
  {
    id: 4,
    username: 'Player 4',
    score: 1250,
    gold: 850,
    elo: getRandomElo(),
    wins: 55,
    losses: 45,
  },
  {
    id: 5,
    username: 'Player 5',
    score: 1200,
    gold: 800,
    elo: getRandomElo(),
    wins: 52,
    losses: 48,
  },
  {
    id: 6,
    username: 'Player 6',
    score: 1150,
    gold: 750,
    elo: getRandomElo(),
    wins: 50,
    losses: 50,
  },
  {
    id: 7,
    username: 'Player 7',
    score: 1100,
    gold: 700,
    elo: getRandomElo(),
    wins: 48,
    losses: 52,
  },
  {
    id: 8,
    username: 'Player 8',
    score: 1050,
    gold: 650,
    elo: getRandomElo(),
    wins: 45,
    losses: 55,
  },
  {
    id: 9,
    username: 'Player 9',
    score: 1000,
    gold: 600,
    elo: getRandomElo(),
    wins: 42,
    losses: 58,
  },
  {
    id: 10,
    username: 'Player 10',
    score: 950,
    gold: 550,
    elo: getRandomElo(),
    wins: 40,
    losses: 60,
  },
  {
    id: 11,
    username: 'Player 11',
    score: 900,
    gold: 500,
    elo: getRandomElo(),
    wins: 38,
    losses: 62,
  },
  {
    id: 12,
    username: 'Player 12',
    score: 850,
    gold: 450,
    elo: getRandomElo(),
    wins: 35,
    losses: 65,
  },
  {
    id: 13,
    username: 'Player 13',
    score: 800,
    gold: 400,
    elo: getRandomElo(),
    wins: 33,
    losses: 67,
  },
  {
    id: 14,
    username: 'Player 14',
    score: 750,
    gold: 350,
    elo: getRandomElo(),
    wins: 30,
    losses: 70,
  },
  {
    id: 15,
    username: 'Player 15',
    score: 700,
    gold: 300,
    elo: getRandomElo(),
    wins: 28,
    losses: 72,
  },
  {
    id: 16,
    username: 'Player 16',
    score: 650,
    gold: 250,
    elo: getRandomElo(),
    wins: 25,
    losses: 75,
  },
  {
    id: 17,
    username: 'Player 17',
    score: 600,
    gold: 200,
    elo: getRandomElo(),
    wins: 22,
    losses: 78,
  },
  {
    id: 18,
    username: 'Player 18',
    score: 550,
    gold: 150,
    elo: getRandomElo(),
    wins: 20,
    losses: 80,
  },
  {
    id: 19,
    username: 'Player 19',
    score: 500,
    gold: 100,
    elo: getRandomElo(),
    wins: 18,
    losses: 82,
  },
  {
    id: 20,
    username: 'Player 20',
    score: 450,
    gold: 50,
    elo: getRandomElo(),
    wins: 15,
    losses: 85,
  },
  {
    id: 21,
    username: 'Player 21',
    score: 400,
    gold: 0,
    elo: getRandomElo(),
    wins: 12,
    losses: 88,
  },
  {
    id: 22,
    username: 'Player 22',
    score: 350,
    gold: -50,
    elo: getRandomElo(),
    wins: 10,
    losses: 90,
  },
  {
    id: 23,
    username: 'Player 23',
    score: 300,
    gold: -100,
    elo: getRandomElo(),
    wins: 8,
    losses: 92,
  },
];

function getRandomElo(): number {
  return Math.floor(Math.random() * 2000) + 1;
}
